version: '3.7'

services:

  fe-app:
    container_name: fe-app
    build:
      context: .
      dockerfile: app.Dockerfile
    command: ng serve --host 0.0.0.0
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'